# Generated by Django 4.0.4 on 2022-12-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allurl',
            name='url',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
